In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


# Creating a Tensor

In [3]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0739e-33, 4.4358e-41]])


In [4]:
#check type
type(a)

torch.Tensor

In [5]:
#using zeroes
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
#using ones
c = torch.ones(2,3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
#using rand
torch.rand(2,3)

tensor([[0.6644, 0.8310, 0.9446],
        [0.4806, 0.6508, 0.6092]])

In [8]:
#using seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#other ways

#arrange
print("using arrange ->", torch.arange(0,10,2))

#using linspace
print("using linspace ->",torch.linspace(0,10,10))

#using eye
print("using eye ->",torch.eye(5)) #identity matrix

#using full
print("using full ->", torch.full((3,3),5))

using arrange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [11]:
x = torch.tensor([[-1,2,3],[4,5,6]])
x

tensor([[-1,  2,  3],
        [ 4,  5,  6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[135961321426416, 135961321426416, 135957189754880],
        [            257,      1095866336,      1095916128]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
#  torch.rand_like(x) # this will generate error because the data type of x is int and rand is float
torch.rand_like(x.to(torch.float))

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [17]:
# find data type
x.dtype

torch.int64

In [18]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
#using to()
x.to(torch.float32)

tensor([[-1.,  2.,  3.],
        [ 4.,  5.,  6.]])

# Mathematical Operations

### 1. Scalar operations

In [21]:
print(x)

#Addition
print("Addition" , x + 2) #adds scalar to every

#subtraction
print("Subtraction" ,x-2)

#multiplication
print("multiplication", x*2)
#division
print("Division" , x/2)

# int division
print("int division", x//2)

#mod
print("mod 2", x%2)

tensor([[-1,  2,  3],
        [ 4,  5,  6]])
Addition tensor([[1, 4, 5],
        [6, 7, 8]])
Subtraction tensor([[-3,  0,  1],
        [ 2,  3,  4]])
multiplication tensor([[-2,  4,  6],
        [ 8, 10, 12]])
Division tensor([[-0.5000,  1.0000,  1.5000],
        [ 2.0000,  2.5000,  3.0000]])
int division tensor([[-1,  1,  1],
        [ 2,  2,  3]])
mod 2 tensor([[1, 0, 1],
        [0, 1, 0]])


In [22]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)



tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [23]:
a+b
a-b
a*b
a/b

a**b

a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [24]:
c = torch.tensor([1,-3,5,-7])

In [25]:
# abs
print(abs(c))


tensor([1, 3, 5, 7])


In [26]:
# negative
d = torch.neg(c)
d

tensor([-1,  3, -5,  7])

In [27]:
# round
torch.round(a)

tensor([[1., 1., 0.],
        [1., 1., 1.]])

In [28]:
# floor and ceil
torch.floor(a)
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
# clamp
torch.clamp(a,min = 0.43, max = 0.5)

tensor([[0.5000, 0.5000, 0.4300],
        [0.5000, 0.5000, 0.5000]])

### Reduction operation

In [30]:
e = torch.randint(size=(2,3),low = 0, high = 10,dtype = torch.float32)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [31]:
#sum
torch.sum(e)

#sum along columns
torch.sum(e,dim = 0)

#sum along rows
torch.sum(e,dim = 1)


tensor([10., 17.])

In [32]:
#mean
torch.mean(e)
torch.mean(e,dim = 0)

tensor([4.5000, 4.5000, 4.5000])

In [33]:
torch.max(e)
torch.min(e)


tensor(0.)

In [34]:
torch.prod(e)

tensor(0.)

In [35]:
# standard deviation
torch.std(e)

#variance
torch.var(e)

tensor(21.1000)

In [36]:
#argmax
torch.argmax(e) #sabse bade wale element ka postion batata hai

tensor(2)

In [37]:
#argmin
torch.argmin(e)

tensor(0)

### Matrix Operations

In [38]:
f = torch.randint(size = (2,3),low = 0 ,high = 10)
g = torch.randint(size = (3,2), low = 0 , high = 10)

print(f)
print(g)

tensor([[7, 0, 0],
        [9, 5, 7]])
tensor([[3, 9],
        [4, 0],
        [5, 7]])


In [39]:
z = torch.matmul(f,g)

In [40]:
vector1 = torch.tensor([1,2],dtype = torch.float32)
vector2 = torch.tensor([3,4],dtype = torch.float32)

#dot product
torch.dot(vector1,vector2)

tensor(11.)

In [41]:
#transpose
f = torch.transpose(f,0,1)
f

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [42]:
#determinant
g = torch.randint(size = (3,3),low = 0 ,high = 10)

torch.det(g.to(torch.float32))

tensor(184.0000)

In [43]:
#inverse
torch.inverse(g.to(torch.float32))

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

### comparison Operation

In [44]:
#greater than
a>b
#less than
a<b
#not equal to
a!=b
#equal to
a==b
#greater than equal to
#less than equal to

tensor([[False, False, False],
        [False, False, False]])

### Special Functions

In [45]:
k = torch.randint(size = (2,3),low = 0,high = 10)
k

tensor([[9, 2, 6],
        [7, 7, 8]])

In [46]:
#log
torch.log(k)

tensor([[2.1972, 0.6931, 1.7918],
        [1.9459, 1.9459, 2.0794]])

In [47]:
#exp
torch.exp(k)

tensor([[8.1031e+03, 7.3891e+00, 4.0343e+02],
        [1.0966e+03, 1.0966e+03, 2.9810e+03]])

In [48]:
#sqrt
torch.sqrt(k)

tensor([[3.0000, 1.4142, 2.4495],
        [2.6458, 2.6458, 2.8284]])

In [49]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.8808, 0.9975],
        [0.9991, 0.9991, 0.9997]])

In [50]:
#softmax
torch.softmax(k.to(torch.float32),dim = 0)

tensor([[0.8808, 0.0067, 0.1192],
        [0.1192, 0.9933, 0.8808]])

In [51]:
#relu
torch.relu(k)

tensor([[9, 2, 6],
        [7, 7, 8]])

### Inplace Operations

In [64]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])
tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])


In [68]:
# m + n

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [69]:
m.add_(n)

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [70]:
m

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [71]:
n

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [72]:
m.relu_()

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

### Copying a Tensor

In [73]:
a = torch.rand(2,3)
a

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [74]:
b=a

In [75]:
a[0][0] = 0

In [76]:
a

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [77]:
b

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [80]:
id(a) == id(b)

True

In [81]:
c = a.clone()

In [82]:
c

tensor([[0.0000, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [83]:
# id(a) == id(b) #True
id(a) == id(c) #False

False

### Tensor Operations on GPU

In [84]:
# torch.cuda.is_available()

False

In [87]:
# device = torch.device('cuda')

In [89]:
# # creating a new tensor on gpu
# torch.rand((2,3),device = device)



In [92]:
# # moving an existing tensor to GPU
# a = torch.rand((2,3))
# a.to(device)

### Reshaping Tensors

In [94]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [100]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
b = torch.rand(2,3,4)
b

tensor([[[0.4890, 0.5887, 0.7340, 0.8497],
         [0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582]],

        [[0.6688, 0.2651, 0.2336, 0.5057],
         [0.5688, 0.0634, 0.8993, 0.2732],
         [0.3397, 0.1879, 0.5534, 0.2682]]])

In [104]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [110]:
#unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])